/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.NhanVienController;
import controller.UserController;
import model.NhanVien;
import model.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

/**
 * @author hiepn
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        setLocationRelativeTo(null);  // hiển thị ở giữa màn hình
        showNhanVienTable();
    }
    private void showNhanVienTable() {
        DefaultTableModel model = NhanVienController.getAllNhanVienTableModel();
        tableNhanVien.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        tbSoDienThoai1 = new javax.swing.JTextField();
        javax.swing.ButtonGroup buttonGroupGioiTinh = new javax.swing.ButtonGroup();
        jPannelDangXuat = new javax.swing.JTabbedPane();
        jTabbedPaneNhanVien = new javax.swing.JTabbedPane();
        jPanelNhanVien = new javax.swing.JPanel();
        btnThemNhanVien = new javax.swing.JButton();
        btnSuaNhanVien = new javax.swing.JButton();
        btnXoaNhanVien = new javax.swing.JButton();
        btnLamTrong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tbMaNhanVien = new javax.swing.JTextField();
        tbTenNhanVien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCalendarNgaySinh = new com.toedter.calendar.JCalendar();
        jLabel9 = new javax.swing.JLabel();
        jCalendarNgayVaoLam = new com.toedter.calendar.JCalendar();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxChucVu = new javax.swing.JComboBox<>();
        tbSoDienThoai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tbDiaChi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaChuThich = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        radNu = new javax.swing.JRadioButton();
        radNam = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jPanelChucVu = new javax.swing.JPanel();
        jTabbedPaneViecLam = new javax.swing.JTabbedPane();
        jTabbedPaneLuong = new javax.swing.JTabbedPane();
        jPanelDoiPass = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tbNhapUsername = new javax.swing.JTextField();
        jtbNhapPasswordcu = new javax.swing.JPasswordField();
        jtbNhapLaiPasswordMoi = new javax.swing.JPasswordField();
        jtbNhapPasswordMoi = new javax.swing.JPasswordField();
        btnThayDoiMatKhau = new javax.swing.JButton();
        jPanelinfo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDangXuat = new javax.swing.JPanel();

        jLabel15.setText("Số điện thoại");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPannelDangXuat.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jPannelDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPannelDangXuat.setMinimumSize(new java.awt.Dimension(1800, 158));
        jPannelDangXuat.setPreferredSize(new java.awt.Dimension(1910, 998));

        jTabbedPaneNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnThemNhanVien.setBackground(new java.awt.Color(0, 255, 0));
        btnThemNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemNhanVien.setText("Thêm");
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });

        btnSuaNhanVien.setBackground(new java.awt.Color(255, 145, 145));
        btnSuaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuaNhanVien.setText("Sửa");
        btnSuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhanVienActionPerformed(evt);
            }
        });

        btnXoaNhanVien.setBackground(new java.awt.Color(255, 0, 0));
        btnXoaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoaNhanVien.setText("Xóa");
        btnXoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhanVienActionPerformed(evt);
            }
        });

        btnLamTrong.setBackground(new java.awt.Color(102, 102, 255));
        btnLamTrong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamTrong.setText("Reset");
        btnLamTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamTrongActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tableNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaNhanVien", "TenNhanVien", "NgaySinh", "GioiTinh", "ChucVu", "SoDienThoai", "NgayVaoLam", "DiaChi", "ChuThich"
            }
        ));
        tableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNhanVien);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mã nhân viên");

        tbMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMaNhanVienActionPerformed(evt);
            }
        });

        tbTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTenNhanVienActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tên nhân viên");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ngày sinh");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Ngày vào làm");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Chức vụ");

        jComboBoxChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kế Toán", "Thu Ngân", "Bảo Vệ", "Giám Đốc", "Null" }));
        jComboBoxChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChucVuActionPerformed(evt);
            }
        });

        tbSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSoDienThoaiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Số điện thoại");

        tbDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDiaChiActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Địa chỉ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Chú thích");

        jTextAreaChuThich.setColumns(20);
        jTextAreaChuThich.setRows(5);
        jScrollPane2.setViewportView(jTextAreaChuThich);

        buttonGroupGioiTinh.add(radNu);
        radNu.setText("Nữ");

        buttonGroupGioiTinh.add(radNam);
        radNam.setText("Nam");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Giới tính");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radNam)
                .addGap(18, 18, 18)
                .addComponent(radNu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radNu)
                    .addComponent(radNam)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanelNhanVienLayout = new javax.swing.GroupLayout(jPanelNhanVien);
        jPanelNhanVien.setLayout(jPanelNhanVienLayout);
        jPanelNhanVienLayout.setHorizontalGroup(
            jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                        .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(24, 24, 24)
                                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbMaNhanVien)
                                    .addComponent(jCalendarNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(tbTenNhanVien))
                                .addGap(32, 32, 32)
                                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCalendarNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(tbSoDienThoai)
                                    .addComponent(jComboBoxChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                                    .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(btnLamTrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelNhanVienLayout.setVerticalGroup(
            jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                        .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxChucVu)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tbTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCalendarNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCalendarNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                        .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        jTabbedPaneNhanVien.addTab("Nhân Viên", jPanelNhanVien);

        javax.swing.GroupLayout jPanelChucVuLayout = new javax.swing.GroupLayout(jPanelChucVu);
        jPanelChucVu.setLayout(jPanelChucVuLayout);
        jPanelChucVuLayout.setHorizontalGroup(
            jPanelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1488, Short.MAX_VALUE)
        );
        jPanelChucVuLayout.setVerticalGroup(
            jPanelChucVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );

        jTabbedPaneNhanVien.addTab("Chức Vụ", jPanelChucVu);

        jPannelDangXuat.addTab("Nhân Viên", new javax.swing.ImageIcon(getClass().getResource("/images/nhanvien.png")), jTabbedPaneNhanVien); // NOI18N
        jPannelDangXuat.addTab("Việc Làm", new javax.swing.ImageIcon(getClass().getResource("/images/congviec.png")), jTabbedPaneViecLam); // NOI18N
        jPannelDangXuat.addTab("Lương", new javax.swing.ImageIcon(getClass().getResource("/images/luong.png")), jTabbedPaneLuong); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Nhập Lại Mật Khẩu Mới");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nhập Mật Khẩu Mới");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Nhập Mật Khẩu Cũ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ĐỔI MẬT KHẨU");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Nhập Tên Tài khoản");

        tbNhapUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNhapUsernameActionPerformed(evt);
            }
        });

        jtbNhapPasswordcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbNhapPasswordcuActionPerformed(evt);
            }
        });

        jtbNhapLaiPasswordMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbNhapLaiPasswordMoiActionPerformed(evt);
            }
        });

        jtbNhapPasswordMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbNhapPasswordMoiActionPerformed(evt);
            }
        });

        btnThayDoiMatKhau.setBackground(new java.awt.Color(255, 153, 153));
        btnThayDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnThayDoiMatKhau.setText("Thay Đổi Mật Khẩu");
        btnThayDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtbNhapPasswordcu)
                            .addComponent(jtbNhapLaiPasswordMoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(jtbNhapPasswordMoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbNhapUsername))
                        .addGap(18, 18, 18)
                        .addComponent(btnThayDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbNhapUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtbNhapPasswordcu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtbNhapPasswordMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnThayDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbNhapLaiPasswordMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(408, 408, 408))
        );

        javax.swing.GroupLayout jPanelDoiPassLayout = new javax.swing.GroupLayout(jPanelDoiPass);
        jPanelDoiPass.setLayout(jPanelDoiPassLayout);
        jPanelDoiPassLayout.setHorizontalGroup(
            jPanelDoiPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoiPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDoiPassLayout.setVerticalGroup(
            jPanelDoiPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoiPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPannelDangXuat.addTab("Đổi Mật Khẩu", new javax.swing.ImageIcon(getClass().getResource("/images/doimatkhau.png")), jPanelDoiPass); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHÓM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1464, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(458, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelinfoLayout = new javax.swing.GroupLayout(jPanelinfo);
        jPanelinfo.setLayout(jPanelinfoLayout);
        jPanelinfoLayout.setHorizontalGroup(
            jPanelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelinfoLayout.setVerticalGroup(
            jPanelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPannelDangXuat.addTab("Thông Tin", new javax.swing.ImageIcon(getClass().getResource("/images/thongtin.png")), jPanelinfo); // NOI18N

        jPanelDangXuat.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelDangXuatComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanelDangXuatLayout = new javax.swing.GroupLayout(jPanelDangXuat);
        jPanelDangXuat.setLayout(jPanelDangXuatLayout);
        jPanelDangXuatLayout.setHorizontalGroup(
            jPanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1488, Short.MAX_VALUE)
        );
        jPanelDangXuatLayout.setVerticalGroup(
            jPanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );

        jPannelDangXuat.addTab("Đăng Xuất", new javax.swing.ImageIcon(getClass().getResource("/images/dangxuat.png")), jPanelDangXuat); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPannelDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 1887, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPannelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelDangXuatComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelDangXuatComponentShown
        // TODO add your handling code here:
        FormDangNhap formDangNhap = new FormDangNhap();
        formDangNhap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelDangXuatComponentShown

    private void btnThayDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiMatKhauActionPerformed
        // TODO add your handling code here:
        // Get input values
        String username = tbNhapUsername.getText();
        String currentPassword = new String(jtbNhapPasswordcu.getPassword());
        String newPassword = new String(jtbNhapPasswordMoi.getPassword());
        String confirmNewPassword = new String(jtbNhapLaiPasswordMoi.getPassword());

        // Validate input
        if (username.isEmpty() || currentPassword.isEmpty() || newPassword.isEmpty() || confirmNewPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!newPassword.equals(confirmNewPassword)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới và xác nhận mật khẩu mới không khớp.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Authenticate user
        User user = new User(0,username,currentPassword);
        if (!UserController.authenticateUser(user)) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu cũ không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Change password
        if (UserController.changePassword(user, newPassword)) {
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi đổi mật khẩu.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThayDoiMatKhauActionPerformed

    private void tbNhapUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNhapUsernameActionPerformed
        // TODO add your handling code here:
        String username = tbNhapUsername.getText();
    }//GEN-LAST:event_tbNhapUsernameActionPerformed

    private void jtbNhapPasswordcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbNhapPasswordcuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbNhapPasswordcuActionPerformed

    private void jtbNhapLaiPasswordMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbNhapLaiPasswordMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbNhapLaiPasswordMoiActionPerformed

    private void jtbNhapPasswordMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbNhapPasswordMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbNhapPasswordMoiActionPerformed

    private void tbTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTenNhanVienActionPerformed
        // TODO add your handling code here:
        String tenNhanVien = tbTenNhanVien.getText();
    }//GEN-LAST:event_tbTenNhanVienActionPerformed

    private void tbMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMaNhanVienActionPerformed
        // TODO add your handling code here:
        String maNhanVien = tbMaNhanVien.getText();
    }//GEN-LAST:event_tbMaNhanVienActionPerformed

    private void jComboBoxChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChucVuActionPerformed
        // TODO add your handling code here:
        String selectedValue = (String) jComboBoxChucVu.getSelectedItem();
    }//GEN-LAST:event_jComboBoxChucVuActionPerformed

    private void tbSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSoDienThoaiActionPerformed
        // TODO add your handling code here:
        String soDienThoai = tbSoDienThoai.getText();
    }//GEN-LAST:event_tbSoDienThoaiActionPerformed

    private void tbDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDiaChiActionPerformed
        // TODO add your handling code here:
        String diaChi = tbDiaChi.getText();
    }//GEN-LAST:event_tbDiaChiActionPerformed

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
        // TODO add your handling code here:
        // Get the values from the input fields
        String maNhanVien = tbMaNhanVien.getText();
        String tenNhanVien = tbTenNhanVien.getText();
        String diaChi = tbDiaChi.getText();
        String soDienThoai = tbSoDienThoai.getText();
        String gioiTinh = radNam.isSelected() ? "Nam" : "Nữ"; // Assuming radNam and radNu are radio buttons
        Date ngaySinh = jCalendarNgaySinh.getDate() != null ? new Date(jCalendarNgaySinh.getDate().getTime()) : null;
        Date ngayVaoLam = jCalendarNgayVaoLam.getDate() != null ? new Date(jCalendarNgayVaoLam.getDate().getTime()) : null;
        String chucVu = jComboBoxChucVu.getSelectedItem().toString();
        String chuThich = jTextAreaChuThich.getText();

        // Check if any of the required fields is empty
        if (maNhanVien.isEmpty() || tenNhanVien.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution
        }

        // Check if MaNhanVien already exists in the database
        NhanVienController nhanVienController = new NhanVienController();
        if (nhanVienController.isMaNhanVienExists(Integer.parseInt(maNhanVien))) {
            JOptionPane.showMessageDialog(this, "MaNhanVien already exists. Please choose a different one.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution
        }

        // Create a new NhanVien object with the retrieved values
        NhanVien newNhanVien = new NhanVien();
        newNhanVien.setMaNhanVien(Integer.parseInt(maNhanVien));
        newNhanVien.setTenNhanVien(tenNhanVien);
        newNhanVien.setDiaChi(diaChi);
        newNhanVien.setSoDienThoai(soDienThoai);
        newNhanVien.setGioiTinh(gioiTinh);
        newNhanVien.setNgaySinh(ngaySinh);
        newNhanVien.setNgayVaoLam(ngayVaoLam);
        newNhanVien.setChucVu(chucVu);
        newNhanVien.setChuThich(chuThich);

        // Call the method to add the new employee to the database
        boolean success = nhanVienController.addNhanVien(newNhanVien);

        if (success) {
            // Employee added successfully, you can display a success message or update the UI
            // Clear the input fields if needed
            clearInputFields();
            JOptionPane.showMessageDialog(this, "Employee added successfully");
            showNhanVienTable();
        } else {
            // Failed to add employee, you can display an error message or handle accordingly
            JOptionPane.showMessageDialog(this, "Failed to add employee. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // Custom method to clear all input fields

    }//GEN-LAST:event_btnThemNhanVienActionPerformed

    private void clearInputFields() {
        // Check if jCalendarNgaySinh and jCalendarNgayVaoLam are not null before using them
//        if (jCalendarNgaySinh != null && jCalendarNgayVaoLam != null) {
//            if (jCalendarNgaySinh.getDate() != null) {
//                jCalendarNgaySinh.setDate(null);
//            }
//
//            if (jCalendarNgayVaoLam.getDate() != null) {
//                jCalendarNgayVaoLam.setDate(null);
//            }
//        }

        // Clear other input fields as needed
        tbMaNhanVien.setText("");
        tbTenNhanVien.setText("");
        tbDiaChi.setText("");
        tbSoDienThoai.setText("");
        radNam.setSelected(true); // Assuming radNam and radNu are radio buttons
        jComboBoxChucVu.setSelectedIndex(4);
        jTextAreaChuThich.setText("");
    }



    private void btnSuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhanVienActionPerformed
        // TODO add your handling code here:
        // Get the values from the input fields
        String maNhanVienStr = tbMaNhanVien.getText();
        String tenNhanVien = tbTenNhanVien.getText();
        String diaChi = tbDiaChi.getText();
        String soDienThoai = tbSoDienThoai.getText();
        String gioiTinh = radNam.isSelected() ? "Nam" : "Nữ";
        Date ngaySinh = jCalendarNgaySinh.getDate() != null ? new Date(jCalendarNgaySinh.getDate().getTime()) : null;
        Date ngayVaoLam = jCalendarNgayVaoLam.getDate() != null ? new Date(jCalendarNgayVaoLam.getDate().getTime()) : null;
        String chucVu = jComboBoxChucVu.getSelectedItem().toString();
        String chuThich = jTextAreaChuThich.getText();

        // Check if the employee ID is empty
        if (maNhanVienStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the employee ID to update.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convert employee ID from string to integer
        try {
            int maNhanVien = Integer.parseInt(maNhanVienStr);

            // Create a new NhanVien object with the retrieved values
            NhanVien updatedNhanVien = new NhanVien();
            updatedNhanVien.setMaNhanVien(maNhanVien);
            updatedNhanVien.setTenNhanVien(tenNhanVien);
            updatedNhanVien.setDiaChi(diaChi);
            updatedNhanVien.setSoDienThoai(soDienThoai);
            updatedNhanVien.setGioiTinh(gioiTinh);
            updatedNhanVien.setNgaySinh(ngaySinh);
            updatedNhanVien.setNgayVaoLam(ngayVaoLam);
            updatedNhanVien.setChucVu(chucVu);
            updatedNhanVien.setChuThich(chuThich);

            // Call the method to update the employee in the database
            NhanVienController nhanVienController = new NhanVienController();
            boolean success = nhanVienController.updateNhanVien(updatedNhanVien);

            if (success) {
                // Employee updated successfully
                JOptionPane.showMessageDialog(this, "Employee updated successfully");
                showNhanVienTable();
                // Clear the input fields or update the UI if needed
            } else {
                // Failed to update employee
                JOptionPane.showMessageDialog(this, "Failed to update employee. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Handle if the employee ID is not a valid number
            JOptionPane.showMessageDialog(this, "Invalid employee ID. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaNhanVienActionPerformed

    private void btnXoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhanVienActionPerformed
        // TODO add your handling code here:
        // Lấy mã nhân viên cần xóa từ trường nhập liệu (ví dụ: tbMaNhanVien)
        String maNhanVienStr = tbMaNhanVien.getText();

        // Kiểm tra xem trường mã nhân viên có rỗng không
        if (maNhanVienStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the employee ID to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Ngừng thực hiện tiếp
        }

        // Chuyển đổi mã nhân viên từ chuỗi sang số nguyên
        try {
            int maNhanVien = Integer.parseInt(maNhanVienStr);

            // Hiển thị hộp thoại xác nhận
            int option = JOptionPane.showConfirmDialog(this, "Do you really want to delete this employee?", "Confirmation", JOptionPane.YES_NO_OPTION);

            // Nếu người dùng chọn YES (đồng ý), thì thực hiện xóa
            if (option == JOptionPane.YES_OPTION) {
                // Gọi phương thức xóa nhân viên từ NhanVienController
                NhanVienController nhanVienController = new NhanVienController();
                boolean success = nhanVienController.deleteNhanVien(maNhanVien);

                if (success) {
                    // Xóa thành công
                    JOptionPane.showMessageDialog(this, "Employee deleted successfully");
                    showNhanVienTable();
                    // Cập nhật giao diện hoặc thực hiện các công việc cần thiết sau khi xóa
                    // Ví dụ: clearInputFields() hoặc load lại danh sách nhân viên
                } else {
                    // Xóa thất bại
                    JOptionPane.showMessageDialog(this, "Failed to delete employee. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            // Xử lý nếu không thể chuyển đổi thành số nguyên
            JOptionPane.showMessageDialog(this, "Invalid employee ID. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaNhanVienActionPerformed

    private void btnLamTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamTrongActionPerformed
        // TODO add your handling code here:
        tbMaNhanVien.setText("");
        tbTenNhanVien.setText("");
        tbDiaChi.setText("");
        tbSoDienThoai.setText("");
        radNam.setSelected(true); // Assuming radNam and radNu are radio buttons
        jComboBoxChucVu.setSelectedIndex(4);
        jTextAreaChuThich.setText("");
    }//GEN-LAST:event_btnLamTrongActionPerformed

    private void tableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhanVienMouseClicked
        // TODO add your handling code here:
        // Lấy chỉ số của dòng được chọn
        int selectedRow = tableNhanVien.getSelectedRow();

        // Kiểm tra xem có dòng nào được chọn không
        if (selectedRow >= 0) {
            // Lấy dữ liệu từ model của bảng
            DefaultTableModel model = (DefaultTableModel) tableNhanVien.getModel();

            // Lấy dữ liệu từ dòng được chọn
            int maNhanVien = (int) model.getValueAt(selectedRow, 0);
            String tenNhanVien = (String) model.getValueAt(selectedRow, 1);
            String diaChi = (String) model.getValueAt(selectedRow, 2);
            String soDienThoai = (String) model.getValueAt(selectedRow, 3);
            String gioiTinh = (String) model.getValueAt(selectedRow, 4);
            Date ngaySinh = (Date) model.getValueAt(selectedRow, 5);
            Date ngayVaoLam = (Date) model.getValueAt(selectedRow, 6);
            String chucVu = (String) model.getValueAt(selectedRow, 7);
            String chuThich = (String) model.getValueAt(selectedRow, 8);

            // Hiển thị dữ liệu lên các ô textbox hoặc nơi khác trên giao diện
            tbMaNhanVien.setText(String.valueOf(maNhanVien));
            tbTenNhanVien.setText(tenNhanVien);
            tbDiaChi.setText(diaChi);
            tbSoDienThoai.setText(soDienThoai);
            if (gioiTinh.equals("Nam")) {
                radNam.setSelected(true);
            } else {
                radNu.setSelected(true);
            }
            jCalendarNgaySinh.setDate(ngaySinh);
            jCalendarNgayVaoLam.setDate(ngayVaoLam);
            jComboBoxChucVu.setSelectedItem(chucVu);
            jTextAreaChuThich.setText(chuThich);
        }
    }//GEN-LAST:event_tableNhanVienMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamTrong;
    private javax.swing.JButton btnSuaNhanVien;
    private javax.swing.JButton btnThayDoiMatKhau;
    private javax.swing.JButton btnThemNhanVien;
    private javax.swing.JButton btnXoaNhanVien;
    private com.toedter.calendar.JCalendar jCalendarNgaySinh;
    private com.toedter.calendar.JCalendar jCalendarNgayVaoLam;
    private javax.swing.JComboBox<String> jComboBoxChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelChucVu;
    private javax.swing.JPanel jPanelDangXuat;
    private javax.swing.JPanel jPanelDoiPass;
    private javax.swing.JPanel jPanelNhanVien;
    private javax.swing.JPanel jPanelinfo;
    private javax.swing.JTabbedPane jPannelDangXuat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneLuong;
    private javax.swing.JTabbedPane jTabbedPaneNhanVien;
    private javax.swing.JTabbedPane jTabbedPaneViecLam;
    private javax.swing.JTextArea jTextAreaChuThich;
    private javax.swing.JPasswordField jtbNhapLaiPasswordMoi;
    private javax.swing.JPasswordField jtbNhapPasswordMoi;
    private javax.swing.JPasswordField jtbNhapPasswordcu;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTable tableNhanVien;
    private javax.swing.JTextField tbDiaChi;
    private javax.swing.JTextField tbMaNhanVien;
    private javax.swing.JTextField tbNhapUsername;
    private javax.swing.JTextField tbSoDienThoai;
    private javax.swing.JTextField tbSoDienThoai1;
    private javax.swing.JTextField tbTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
